-- Test verileri

-- Şirketler
INSERT OR IGNORE INTO companies (company_code, company_name, tax_number) VALUES
('OLKA', 'OLKA SPOR MALZEMELERİ TİC. A.Ş.', NULL),
('MARLIN', 'MARLIN SPOR MALZEMELERI TICARET A.Ş.', NULL),
('JUPITER', 'JÜPİTER MODA VE SPOR MALZEMELERİ TİCARET A.Ş.', NULL),
('NEPTUN', 'NEPTÜN SPOR MALZEMELERİ TİCARET A.Ş.', NULL),
('SATURN', 'SATÜRN SPOR MALZEMELERİ TİCARET A.Ş.', NULL);

-- Tedarikçiler
INSERT OR IGNORE INTO suppliers (supplier_code, supplier_name, company_id, contact_person, email, phone, address, tax_number) VALUES
-- OLKA Tedarikçileri (company_id = 1)
('OLKA001', 'HOPE FAITH LIMITED', 1, NULL, NULL, NULL, NULL, NULL),
('OLKA002', 'HONG KONG GREAT CONTINENT TRADING CO.LIMITED', 1, NULL, NULL, NULL, NULL, NULL),
('OLKA003', 'XIAMEN MEIZHOU IMPORT & EXPORT CO., LTD', 1, NULL, NULL, NULL, NULL, NULL),
('OLKA004', 'SATS WORK EGITIM LIMITED SIRKETI', 1, NULL, NULL, NULL, NULL, NULL),
('OLKA005', 'PAMUSAN NATURAL TEKSTİL DIŞ TİCARET LİMİTED ŞİRKETİ', 1, NULL, NULL, NULL, NULL, NULL),
('OLKA006', 'BENEFIT SYSTEMS SPOR HİZMETLERİ LİMİTED ŞİRKETİ', 1, NULL, NULL, NULL, NULL, NULL),
('OLKA007', 'MEHMET CİHAT KÖSE - MARKALAB', 1, NULL, NULL, NULL, NULL, NULL),
('OLKA008', 'ZEYNEP PEKER - MARKALAB', 1, NULL, NULL, NULL, NULL, NULL),
('OLKA009', 'EDA ÖZDEMİR - MARKALAB', 1, NULL, NULL, NULL, NULL, NULL),
('OLKA010', 'BENER ATİLA - MARKALAB', 1, NULL, NULL, NULL, NULL, NULL),

-- Marlin Tedarikçileri (company_id = 2)
('MARLIN002', 'AYPLASTİK AMBALAJ SANAYİ VE TİCARET A.Ş', 2, NULL, NULL, NULL, NULL, NULL),
('MARLIN003', 'PİR-İNCİ BUJİTERİ İMALAT SANAYİİ TİCARET ANONİM ŞİRKETİ', 2, NULL, NULL, NULL, NULL, NULL),
('MARLIN004', 'RDS GAYRİMENKUL DANIŞMANLIK A.Ş.-GÜRSOY PROJE GELİŞTİRME A.Ş. ADİ ORTAKLIĞI', 2, NULL, NULL, NULL, NULL, NULL),
('MARLIN005', 'VOLÜME MÜHENDİSLİK SANAYİ VE TİCARET LİMİTED ŞİRKETİ', 2, NULL, NULL, NULL, NULL, NULL),
('MARLIN006', 'KORAY YAKICI', 2, NULL, NULL, NULL, NULL, NULL),
('MARLIN007', 'EMEK 1969 PASTACILIK ANONİM ŞİRKETİ', 2, NULL, NULL, NULL, NULL, NULL),
('MARLIN008', 'SÜRTAŞ MADENİ VE PLASTİK EŞYA İMALAT İHRACAT İTHALAT SANAYİ VE TİCARET ANONİM ŞİRKETİ', 2, NULL, NULL, NULL, NULL, NULL),
('MARLIN009', 'ATS GRUP TEMİZLİK ORGANİZASYON GIDA VE TİCARET LİMİTED ŞİRKETİ', 2, NULL, NULL, NULL, NULL, NULL),
('MARLIN010', 'OKYANUS RFID ETİKET MATBAACILIK SANAYİ VE TİCARET LİMİTED ŞİRKETİ', 2, NULL, NULL, NULL, NULL, NULL),

-- Jüpiter Tedarikçileri (company_id = 3)
('JUPITER001', 'MONEYPAY ÖDEME VE ELEKTRONİK PARA HİZMETLERİ ANONİM ŞİRKETİ', 3, NULL, NULL, NULL, NULL, NULL),
('JUPITER002', 'ERE AVM İNŞAAT ANONİM ŞİRKETİ', 3, NULL, NULL, NULL, NULL, NULL),
('JUPITER003', 'KİWİ MEDYA PAZARLAMA ANONİM ŞİRKETİ', 3, NULL, NULL, NULL, NULL, NULL),
('JUPITER004', 'VIBE520 MEDIA REKLAM KOZMETİK LİMİTED ŞİRKETİ', 3, NULL, NULL, NULL, NULL, NULL),
('JUPITER007', 'ZEYNEP BİLGE ERCAN / JOEL YARATICI TASARIM HİZMETLERİ', 3, NULL, NULL, NULL, NULL, NULL),
('JUPITER008', 'MEVSİM OLUKLU MUKAVVA AMBALAJ SANAYİ TİCARET LİMİTED ŞİRKETİ', 3, NULL, NULL, NULL, NULL, NULL),
('JUPITER009', 'U2 DİGİTAL MEDYA HİZMETLERİ A.Ş.', 3, NULL, NULL, NULL, NULL, NULL),
('JUPITER010', 'SAMİ SOYDAN / TEKNO KIRTASİYE', 3, NULL, NULL, NULL, NULL, NULL),

-- Neptün Tedarikçileri (company_id = 4)
('NEPTUN002', 'TEKNO KIRTASİYE', 4, NULL, NULL, NULL, NULL, NULL),
('NEPTUN003', 'BELİEVE MATBAACILIK PROMOSYON REKLAM PAZARLAMA SANAYİ TİCARET LİMİTED ŞİRKETİ', 4, NULL, NULL, NULL, NULL, NULL),
('NEPTUN004', 'ORANSAY TURİZM GIDA SANAYİ VE TİCARET LİMİTED ŞİRKETİ', 4, NULL, NULL, NULL, NULL, NULL),
('NEPTUN005', 'ESATECH GÜÇ SİSTEMLERİ SANAYİ VE TİCARET LİMİTED ŞİRKETİ', 4, NULL, NULL, NULL, NULL, NULL),
('NEPTUN006', 'TURK FİNANSAL TEKNOLOJİ ANONİM ŞİRKETİ', 4, NULL, NULL, NULL, NULL, NULL),
('NEPTUN007', 'EROL TUZGU', 4, NULL, NULL, NULL, NULL, NULL),
('NEPTUN008', 'LİMAN RESTORANT ÖMER YÜCE', 4, NULL, NULL, NULL, NULL, NULL),
('NEPTUN009', 'D-MARKET ELEKTRONİK HİZMETLER VE TİCARET ANONİM ŞİRKETİ', 4, NULL, NULL, NULL, NULL, NULL),
('NEPTUN010', 'CANDAN TURİZM VE TİCARET LİMİTED ŞİRKETİ', 4, NULL, NULL, NULL, NULL, NULL),

-- Satürn Tedarikçileri (company_id = 5)
('SATURN002', 'RAMAZAN KIRKBINAR', 5, NULL, NULL, NULL, NULL, NULL),
('SATURN003', 'ZÜMPA DAYANIKLI TÜKETİM MALLARI SANAYİ VE TİCARET LİMİTED ŞİRKETİ', 5, NULL, NULL, NULL, NULL, NULL),
('SATURN004', 'VOLTRON SOLUTION EĞİTİM DANIŞMANLIK VE BİLİŞİM HİZMETLERİ LİMİTED ŞİRKETİ', 5, NULL, NULL, NULL, NULL, NULL),
('SATURN005', 'BEYAZ FIRIN GIDA VE İHTİYAÇ MAD.SAN.VE TİC.A.Ş.', 5, NULL, NULL, NULL, NULL, NULL),
('SATURN006', 'TALAY LOJISTIK ANONIM SIRKETI', 5, NULL, NULL, NULL, NULL, NULL),
('SATURN007', 'YALIN ANALİZ HİZMETLERİ ANONİM ŞİRKETİ', 5, NULL, NULL, NULL, NULL, NULL),
('SATURN008', 'BV CPS TEST LABORATUVARLARI LTD. ŞTİ.', 5, NULL, NULL, NULL, NULL, NULL),
('SATURN009', 'SANİYE CANAN VARAN VAROL', 5, NULL, NULL, NULL, NULL, NULL),
('SATURN010', 'CANKIZ ALPER BİNZAT', 5, NULL, NULL, NULL, NULL, NULL);

-- Test verileri kaldırıldı (İrsaliye belgeleri, detayları, faturalar ve hesaplamalar)
